export default function Home() {
  const checkoutUrl = process.env.NEXT_PUBLIC_LS_CHECKOUT_URL || '#';

  return (
    <main className="min-h-screen bg-[#0d1117] text-[#c9d1d9]">
      {/* Hero */}
      <section className="max-w-4xl mx-auto px-6 pt-24 pb-20 text-center">
        <div className="inline-block bg-[#161b22] border border-[#30363d] rounded-full px-4 py-1 text-sm text-[#58a6ff] mb-6">
          Browser Extension + Web App
        </div>
        <h1 className="text-4xl md:text-6xl font-bold text-white mb-6 leading-tight">
          Record Browser Actions into{' '}
          <span className="text-[#58a6ff]">Automation Scripts</span>
        </h1>
        <p className="text-lg text-[#8b949e] max-w-2xl mx-auto mb-10">
          Install the extension, click record, and interact with any website. StepRecorder generates clean Puppeteer and Playwright scripts with smart selectors — ready to run or customize.
        </p>
        <div className="flex flex-col sm:flex-row gap-4 justify-center">
          <a
            href={checkoutUrl}
            className="bg-[#58a6ff] hover:bg-[#79b8ff] text-[#0d1117] font-semibold px-8 py-3 rounded-lg transition-colors text-lg"
          >
            Start Recording — $22/mo
          </a>
          <a
            href="#how-it-works"
            className="border border-[#30363d] hover:border-[#58a6ff] text-[#c9d1d9] px-8 py-3 rounded-lg transition-colors text-lg"
          >
            See How It Works
          </a>
        </div>
        <div className="mt-16 bg-[#161b22] border border-[#30363d] rounded-xl p-6 text-left font-mono text-sm">
          <div className="flex gap-2 mb-4">
            <span className="w-3 h-3 rounded-full bg-[#ff5f57]"></span>
            <span className="w-3 h-3 rounded-full bg-[#febc2e]"></span>
            <span className="w-3 h-3 rounded-full bg-[#28c840]"></span>
          </div>
          <pre className="text-[#8b949e] overflow-x-auto"><code>{`// Generated by StepRecorder
const { chromium } = require('playwright');

(async () => {
  const browser = await chromium.launch();
  const page = await browser.newPage();
  await page.goto('https://example.com');
  await page.click('[data-testid="login-btn"]');
  await page.fill('#email', 'user@example.com');
  await page.fill('#password', '••••••••');
  await page.click('button[type="submit"]');
  await browser.close();
})();`}</code></pre>
        </div>
      </section>

      {/* How It Works */}
      <section id="how-it-works" className="max-w-4xl mx-auto px-6 py-16">
        <h2 className="text-2xl font-bold text-white text-center mb-12">How It Works</h2>
        <div className="grid md:grid-cols-3 gap-6">
          {[
            { step: '01', title: 'Install Extension', desc: 'Add StepRecorder to Chrome or Firefox in one click.' },
            { step: '02', title: 'Record Actions', desc: 'Click record, interact with any site — clicks, typing, navigation all captured.' },
            { step: '03', title: 'Export Script', desc: 'Get a clean Puppeteer or Playwright script with smart, resilient selectors.' }
          ].map(({ step, title, desc }) => (
            <div key={step} className="bg-[#161b22] border border-[#30363d] rounded-xl p-6">
              <div className="text-[#58a6ff] font-mono text-sm mb-3">{step}</div>
              <h3 className="text-white font-semibold text-lg mb-2">{title}</h3>
              <p className="text-[#8b949e] text-sm">{desc}</p>
            </div>
          ))}
        </div>
      </section>

      {/* Pricing */}
      <section id="pricing" className="max-w-4xl mx-auto px-6 py-16">
        <h2 className="text-2xl font-bold text-white text-center mb-4">Simple Pricing</h2>
        <p className="text-[#8b949e] text-center mb-12">Everything you need to automate your browser workflows.</p>
        <div className="max-w-sm mx-auto bg-[#161b22] border-2 border-[#58a6ff] rounded-2xl p-8">
          <div className="text-[#58a6ff] font-semibold text-sm mb-2">PRO PLAN</div>
          <div className="flex items-end gap-1 mb-6">
            <span className="text-5xl font-bold text-white">$22</span>
            <span className="text-[#8b949e] mb-2">/month</span>
          </div>
          <ul className="space-y-3 mb-8">
            {[
              'Unlimited script recordings',
              'Puppeteer & Playwright export',
              'Smart selector generation',
              'Script editor & management',
              'Chrome & Firefox extension',
              'Priority support'
            ].map((feature) => (
              <li key={feature} className="flex items-center gap-3 text-sm">
                <span className="text-[#58a6ff] font-bold">✓</span>
                <span className="text-[#c9d1d9]">{feature}</span>
              </li>
            ))}
          </ul>
          <a
            href={checkoutUrl}
            className="block w-full bg-[#58a6ff] hover:bg-[#79b8ff] text-[#0d1117] font-semibold py-3 rounded-lg text-center transition-colors"
          >
            Get Started Now
          </a>
          <p className="text-[#8b949e] text-xs text-center mt-4">Cancel anytime. No contracts.</p>
        </div>
      </section>

      {/* FAQ */}
      <section className="max-w-2xl mx-auto px-6 py-16">
        <h2 className="text-2xl font-bold text-white text-center mb-10">FAQ</h2>
        <div className="space-y-6">
          <div className="bg-[#161b22] border border-[#30363d] rounded-xl p-6">
            <h3 className="text-white font-semibold mb-2">Which browsers and frameworks are supported?</h3>
            <p className="text-[#8b949e] text-sm">The extension works on Chrome and Firefox. Scripts can be exported for both Puppeteer and Playwright — just pick your preferred framework before exporting.</p>
          </div>
          <div className="bg-[#161b22] border border-[#30363d] rounded-xl p-6">
            <h3 className="text-white font-semibold mb-2">How does smart selector generation work?</h3>
            <p className="text-[#8b949e] text-sm">StepRecorder prioritizes stable selectors like data-testid, aria labels, and unique IDs over fragile CSS paths. This makes your scripts resilient to minor UI changes.</p>
          </div>
          <div className="bg-[#161b22] border border-[#30363d] rounded-xl p-6">
            <h3 className="text-white font-semibold mb-2">Can I edit scripts after recording?</h3>
            <p className="text-[#8b949e] text-sm">Yes. The web app includes a full script editor where you can modify, rename, organize, and re-export your recordings at any time.</p>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t border-[#30363d] py-8 text-center text-[#8b949e] text-sm">
        <p>© {new Date().getFullYear()} StepRecorder. Built for QA engineers and developers.</p>
      </footer>
    </main>
  );
}
